[features]
seeds = false
skip-lint = false
[programs.localnet]
liquidity_pool = "D93ohndEaB4in7tJcwSobCX4uUyfTpayCuwS9rvJXz2A"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/satyam/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
